### ISSUE TITLE
exfat 1.2.9

### ISSUE THREAD

**Issue by umerov1999** [dorimanx/exfat-nofuse#102]
Samsung updated exfat to 1.2.24, but your exfat is has old version

**Comment by ismail** [comment]
@umerov1999 Can you post the samsung kernel source link that you are using?

**Comment by umerov1999** [comment]
https://github.com/jcadduono/linux_fs_exfat

**Comment by ismail** [comment]
@umerov1999 I mean an original release from Samsung itself.

**Comment by umerov1999** [comment]
Samsung has removed exfat source from http://opensource.samsung.com. This is original source https://github.com/jcadduono/linux_fs_exfat/tree/samsung

**Comment by diizzyy** [comment]
@ismail 
http://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=F&searchValue=%20SM-G390F has 1.2.24 included

**Comment by ismail** [comment]
@diizzyy Very nice! @dorimanx I think we should synchronize with the latest release.

**Comment by diizzyy** [comment]
Agreed, it's beyond my abilities however...

**Comment by diizzyy** [comment]
@dorimanx 
Is this something you can have a look at?

**Comment by diizzyy** [comment]
Seems to be done here:
https://github.com/coolshou/exfat

**Comment by dorimanx** [comment]
this is old driver, missing tons of changes already done here. i cant sync it.
This driver is open source, if you like to update it, i will be happy to review the changes, make sure its working!
And merge your pull request. till then, i have other things to do.
Driver is OK as is. some issues are found on different linux builds, but they found only there. so not all depend on driver, FS changes in Linux kernel are very important too.
