### ISSUE TITLE
Linux 4.10 compatibility

### ISSUE THREAD

**Issue by FadeMind** [dorimanx/exfat-nofuse#103]
It is look like current exfat-nofuse code is not compatible with upcomming 4.10 release of Linux Kernel. After applying patch kernel build fails in exfat build.

@dorimanx Regards

**Comment by makefu** [comment]
Having the same issue in NixOS Distribution ( http://hydra.nixos.org/build/49438280/nixlog/1 )

**Comment by dorimanx** [comment]
i guess it's fixed by this commit.
https://github.com/dorimanx/exfat-nofuse/commit/a15579ed9e55fea30bf322a13f406b32deb8ffc3
Thanks to autor.

**Comment by makefu** [comment]
looks good, when i get the time i will test on nixOS
