### ISSUE TITLE
Please provide tags for releases

### ISSUE THREAD

**Issue by beku** [dorimanx/exfat-nofuse#106]
Most Linux distributions work with project releases. Release numbers provides downstream with a easy to read and write naming of the projects. Distribution patches are much easier to handle with a proper release number a the belonging source package.

For instance openSUSE has packages in OBS with v1.2.9 . I have no idea to which git sha it relates. That's a problem.

Thanks for your work and for considering.

**Comment by dorimanx** [comment]
this build is not changed for long time now. i know there is more updated build source.
And i will need to rebase all code again.

Question is it really needed... not sure.
So for now there is no need for any TAGS.
All fixes are more compatability fixes.

When i will have time to update to more recent build. and keep all fixes intact. i will provide build tags.
