### ISSUE TITLE
make fails on 4.11 kernel (Fedora Rawhide) with incompatible pointer type errors

### ISSUE THREAD

**Issue by sarangnemo** [dorimanx/exfat-nofuse#107]
I am running kernel 4.11.0-0.rc1.git2.2.fc27.x86_64 (Fedora Rawhide).

"make" fails with the following output:

make -C /lib/modules/4.11.0-0.rc1.git2.2.fc27.x86_64/build M=/home/sarang/build/exfat-nofuse modules
make[1]: Entering directory '/usr/src/kernels/4.11.0-0.rc1.git2.2.fc27.x86_64'
  CC [M]  /home/sarang/build/exfat-nofuse/exfat_super.o
/home/sarang/build/exfat-nofuse/exfat_super.c:1388:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .getattr       = exfat_getattr,
                   ^~~~~~~~~~~~~
/home/sarang/build/exfat-nofuse/exfat_super.c:1388:19: note: (near initialization for ‘exfat_dir_inode_operations.getattr’)
/home/sarang/build/exfat-nofuse/exfat_super.c:1516:17: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .getattr     = exfat_getattr,
                 ^~~~~~~~~~~~~
/home/sarang/build/exfat-nofuse/exfat_super.c:1516:17: note: (near initialization for ‘exfat_file_inode_operations.getattr’)
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/home/sarang/build/exfat-nofuse/exfat_super.o' failed
make[2]: *** [/home/sarang/build/exfat-nofuse/exfat_super.o] Error 1
Makefile:1496: recipe for target '_module_/home/sarang/build/exfat-nofuse' failed
make[1]: *** [_module_/home/sarang/build/exfat-nofuse] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.11.0-0.rc1.git2.2.fc27.x86_64'
Makefile:36: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dorimanx** [comment]
Fixed by this commit:
https://github.com/dorimanx/exfat-nofuse/commit/0c04c398c56cd942e3c7936d6560782a1308b782
Thanks to author!
