### ISSUE TITLE
CURRENT_TIME_SEC removed with Linux 4.12

### ISSUE THREAD

**Issue by rathsky** [dorimanx/exfat-nofuse#113]
Build fails as eg. [CURRENT_TIME_SEC has been removed](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bfe1c566453a0979c0b3cd3728d0de962272f034) in Linux 4.12.

For the replacements, see eg. the parent commits such as [this one](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=607a11ad947794d0f4f2c0f73c654876d1abb9b1).

**Comment by dorimanx** [comment]
was been fixed here:
https://github.com/dorimanx/exfat-nofuse/commit/1e91a9feb0e45161d3c02f9257a9b6c44b9e2739
Thanks to author.
