### ISSUE TITLE
Suggest moving tree to subdirectory

### ISSUE THREAD

**Issue by ehem** [dorimanx/exfat-nofuse#115]
I'd like to suggest moving the tree to a fs/exfat/ directory to ease merging with external trees.

When building as part of a kernel tree you want to move all the files to that subdirectory.  Having all the files already there makes merging while keeping history much simpler.  Merging with history is doable:
```
git merge -s ours --no-commit exfat
git read-tree --prefix=fs/exfat/ -u exfat
ed fs/Kconfig fs/Makefile
git add fs/Kconfig fs/Makefile
git commit
```

But that is a bit of an operation.  Subsequent merges as exfat-nofuse are similarly interesting.

**Comment by dorimanx** [comment]
I do understand your reason. but i must decline. this driver used by many, and it's simple to copy paste all files to folders.
to rebase all git just for that and make other people that use it as external module copy paste,
is just not adding any improvment.

Lets just leave it alone.
Thanks for suggestion.
