### ISSUE TITLE
out of range error?

### ISSUE THREAD

**Issue by colthreepv** [dorimanx/exfat-nofuse#27]
```
[ 5898.848395] [EXFAT] free_cluster : skip free-req clu:64326, because of zero-size truncation
[ 7730.164116] [EXFAT] free_cluster : skip free-req clu:64833, because of zero-size truncation
[42882.817660] EXT4-fs (sdc1): mounted filesystem with ordered data mode. Opts: (null)
[47876.627666] [EXFAT] sector_read: out of range error! (sec = 1589460992)
[47876.627670] [EXFAT] Filesystem has been set read-only
```

that's all the EXFAT messages into `dmesg`, i was transferring ~700gb from an ext partition to an EXFAT, it interrupted at 35% with this issue and mounting itself as RO (without notifying the operating system that still thinks it's mounted rw!)

Anyone had similar issue?

**Comment by sayidGitHub** [comment]
hi，colthreepv
I  also had the same error,"sector_read: out of range error!",are u solve this ? 2017.6.13

**Comment by LittleWhole** [comment]
Had this error today too, 2020.7.13
