### ISSUE TITLE
Teaming up for NTFS

### ISSUE THREAD

**Issue by rxrz** [dorimanx/exfat-nofuse#33]
Hello, Developers!

We're teaming up to rewrite and complete the native NTFS Linux driver.

Please, drop a line to rzrx [a] hush.ai if you would like to be a part of the https://github.com/rxrz/NTFS-defused project.

@lqs and @benpicco: I sent you the invitation emails before, but not sure if you got them. Could you please let me know?

Thank you.

**Comment by gzg1984** [comment]
sadly found this so late. Do you guys still work on this?

**Comment by gzg1984** [comment]
I write some driver code about seven years ago and now I want to complete it.

**Comment by gzg1984** [comment]
seems you guys stoped 4 years ago.
I am forking your project. 
If you guys want to continue to complete it, please send message to me, thanks!
