### ISSUE TITLE
Kernel panic on android mtk 3.4.67

### ISSUE THREAD

**Issue by Niorix** [dorimanx/exfat-nofuse#56]
Module build and insmod work propertly, but on mount device device reboots
root@U65GT:/system/lib/modules # uname -a
Linux localhost 3.4.67 #1 SMP PREEMPT Tue Nov 11 14:26:57 CST 2014 armv7l GNU/Linux
root@U65GT:/system/lib/modules # cat /proc/filesystems
nodev   sysfs
nodev   rootfs
nodev   bdev
nodev   proc
nodev   cgroup
nodev   tmpfs
nodev   debugfs
nodev   sockfs
nodev   pipefs
nodev   anon_inodefs
nodev   devpts
        ext3
        ext4
nodev   ramfs
        vfat
        msdos
        iso9660
        fuseblk
nodev   fuse
nodev   fusectl
nodev   selinuxfs
nodev   mtd_inodefs
nodev   functionfs
root@U65GT:/system/lib/modules # insmod exfat.ko ; dmesg | grep -i exfat
<6>[  357.474296] 1[5567:insmod]exFAT: Version 1.2.9
root@U65GT:/system/lib/modules # cat /proc/filesystems
nodev   sysfs
nodev   rootfs
nodev   bdev
nodev   proc
nodev   cgroup
nodev   tmpfs
nodev   debugfs
nodev   sockfs
nodev   pipefs
nodev   anon_inodefs
nodev   devpts
        ext3
        ext4
nodev   ramfs
        vfat
        msdos
        iso9660
        fuseblk
nodev   fuse
nodev   fusectl
nodev   selinuxfs
nodev   mtd_inodefs
nodev   functionfs
        exfat
mount -t exfat /dev/block/vold/179\:97 /mnt/secure/staging/

At this point, the device is restarted. After rebooting, I do

root@U65GT:/storage/sdcard0 # cat /proc/last_kmsg
ram console header, hw_status: 2, fiq step 40.
bin log 0.
ng                 : 0
[  650.248919] \(2\)[13186:mount]  .rt_throttled                  : 0
[  650.248931] \(2\)[13186:mount]  .rt_time                       : 0.000000
[  650.248944] \(2\)[13186:mount]  .rt_runtime                    : 700.000000
[  650.248957] \(2\)[13186:mount]
[  650.248961] \(2\)[13186:mount]rt_rq[7]:/apps
[  650.248973] \(2\)[13186:mount]  .rt_nr_running                 : 0
[  650.248985] \(2\)[13186:mount]  .rt_throttled                  : 0
[  650.248997] \(2\)[13186:mount]  .rt_time                       : 0.000000
[  650.249010] \(2\)[13186:mount]  .rt_runtime                    : 800.000000
[  650.249022] \(2\)[13186:mount]
[  650.249027] \(2\)[13186:mount]rt_rq[7]:/
[  650.249038] \(2\)[13186:mount]  .rt_nr_running                 : 0
[  650.249050] \(2\)[13186:mount]  .rt_throttled                  : 0
[  650.249062] \(2\)[13186:mount]  .rt_time                       : 0.000000
[  650.249075] \(2\)[13186:mount]  .rt_runtime                    : 950.000000
[  650.249088] \(2\)[13186:mount]
[  650.249092] \(2\)[13186:mount]runnable tasks:
[  650.249097] \(2\)[13186:mount]            task   PID         tree-key  switches  prio     exec-runtime         sum-exec        sum-sleep
[  650.249107] \(2\)[13186:mount]----------------------------------------------------------------------------------------------------------
[  650.259260] \(2\)[13186:mount]==========================================================================================================
[  650.259274] \(2\)[13186:mount]
[  650.259435] \(2\)[13186:mount]-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  650.616444] \(2\)[13186:mount][aee/ipanic] pc/lr/sp 0xb6ea90a0/0xb6f2b187/0xbed84b60
[  650.616730] \(2\)[13186:mount][aee/ipanic] Dump stack range \(0xbed84b60:0xbed85000\)
[  650.616758] \(2\)[13186:mount][aee/ipanic] copy_from_user ret\(0x00000000\),len:4a0
[  650.625062] \(2\)[13186:mount]-=-=-=
[  650.635890] \(2\)[13186:mount]-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  650.971031] \(2\)[13186:mount]-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  651.299878] \(2\)[13186:mount]-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  651.635874] \(2\)[13186:mount]-=
[  651.636498] \(2\)[13186:mount][aee/ipanic] aee-ipanic: Panic dump sucessfully written to emmc \(detail len: 11537, console len: 262144\)
[  651.636520] \(2\)[13186:mount][aee/ipanic] android log : 0x46200, 0x40000, 0x0, 0x0, 0x86200, 0x40000, 0xc6200, 0x40000
[  651.636537] \(2\)[13186:mount][aee/ipanic] mmprofile: offset:0x106200, len:0x0
[  651.636552] \(2\)[13186:mount]Rebooting in 1 seconds..machine_shutdown: start, Proess\(mount:13186\)
[  652.634267] \(2\)[13186:mount]Backtrace:
[  652.634295] \(2\)[13186:mount][\<c001224c\>] \(dump_backtrace+0x0/0x10c\) from [\<c06fc8a0\>] \(dump_stack+0x18/0x1c\)
[  652.634310] \(2\)[13186:mount] r6:000003e8 r5:00000000 r4:000003e8 r3:c09e6018
[  652.634352] \(2\)[13186:mount][\<c06fc888\>] \(dump_stack+0x0/0x1c\) from [\<c000f844\>] \(machine_shutdown+0x34/0x50\)
[  652.634381] \(2\)[13186:mount][\<c000f810\>] \(machine_shutdown+0x0/0x50\) from [\<c000f8bc\>] \(machine_restart+0x14/0x64\)
[  652.634411] \(2\)[13186:mount][\<c000f8a8\>] \(machine_restart+0x0/0x64\) from [\<c0068038\>] \(emergency_restart+0x1c/0x20\)
[  652.634426] \(2\)[13186:mount] r5:00000000 r4:000003e8
[  652.634458] \(2\)[13186:mount][\<c006801c\>] \(emergency_restart+0x0/0x20\) from [\<c06fcd80\>] \(panic+0x138/0x1a0\)
[  652.634485] \(2\)[13186:mount][\<c06fcc48\>] \(panic+0x0/0x1a0\) from [\<c0012524\>] \(die+0x118/0x2ac\)
[  652.634499] \(2\)[13186:mount] r3:00000001 r2:ca6efb60 r1:20070193 r0:c0852b08
[  652.634528] \(2\)[13186:mount] r7:00000001
[  652.634556] \(2\)[13186:mount][\<c001240c\>] \(die+0x0/0x2ac\) from [\<c06fc900\>] \(__do_kernel_fault.part.10+0x5c/0x7c\)
[  652.634583] \(2\)[13186:mount][\<c06fc8a4\>] \(__do_kernel_fault.part.10+0x0/0x7c\) from [\<c0015cc0\>] \(do_page_fault+0x224/0x270\)
[  652.634599] \(2\)[13186:mount] r7:cb36e1c0 r3:ca6efd70
[  652.634630] \(2\)[13186:mount][\<c0015a9c\>] \(do_page_fault+0x0/0x270\) from [\<c0015e34\>] \(do_translation_fault+0xa0/0xa8\)
[  652.634657] \(2\)[13186:mount][\<c0015d94\>] \(do_translation_fault+0x0/0xa8\) from [\<c00083ec\>] \(do_DataAbort+0x78/0x110\)
[  652.634672] \(2\)[13186:mount] r7:c09da8e4 r6:ca6ee000 r5:00000005 r4:ca6efd70
[  652.634713] \(2\)[13186:mount][\<c0008374\>] \(do_DataAbort+0x0/0x110\) from [\<c000e258\>] \(__dabt_svc+0x38/0x60\)
[  652.634729] \(2\)[13186:mount]Exception stack\(0xca6efd70 to 0xca6efdb8\)
[  652.634744] \(2\)[13186:mount]fd60:                                     ffffffff c570c100 00000001 00000000
[  652.634764] \(2\)[13186:mount]fd80: c570c0ec bf05fa1c cc7ca800 c5708000 00000001 00000003 00000000 ca6efe2c
[  652.634782] \(2\)[13186:mount]fda0: 00000000 ca6efdb8 c00e8434 bf059254 60070013 ffffffff
[  652.634795] \(2\)[13186:mount] r8:00000001 r7:ca6efda4 r6:ffffffff r5:60070013 r4:bf059254
[  652.634867] \(2\)[13186:mount][\<bf0591a0\>] \(exfat_fill_super+0x0/0x4b4 [exfat]\) from [\<c011acbc\>] \(mount_bdev+0x174/0x1dc\)
[  652.634911] \(2\)[13186:mount][\<c011ab48\>] \(mount_bdev+0x0/0x1dc\) from [\<bf059198\>] \(exfat_fs_mount+0x20/0x28 [exfat]\)
[  652.634955] \(2\)[13186:mount][\<bf059178\>] \(exfat_fs_mount+0x0/0x28 [exfat]\) from [\<c011b784\>] \(mount_fs+0x4c/0x194\)
[  652.634984] \(2\)[13186:mount][\<c011b738\>] \(mount_fs+0x0/0x194\) from [\<c0133b1c\>] \(vfs_kern_mount+0x50/0xe8\)
[  652.635010] \(2\)[13186:mount][\<c0133acc\>] \(vfs_kern_mount+0x0/0xe8\) from [\<c0134724\>] \(do_kern_mount+0x38/0xfc\)
[  652.635025] \(2\)[13186:mount] r8:d8566380 r7:00008000 r6:d8566900 r5:bf05fa24 r4:00000000
[  652.635056] \(2\)[13186:mount]r3:00000000
[  652.635084] \(2\)[13186:mount][\<c01346ec\>] \(do_kern_mount+0x0/0xfc\) from [\<c0135fc4\>] \(do_mount+0x334/0x854\)
[  652.635098] \(2\)[13186:mount] r8:d8566900 r7:00000020 r6:00000000 r5:00000000 r4:00008000
[  652.635130] \(2\)[13186:mount]r3:00000000
[  652.635157] \(2\)[13186:mount][\<c0135c90\>] \(do_mount+0x0/0x854\) from [\<c0136640\>] \(sys_mount+0x8c/0xc0\)
[  652.635183] \(2\)[13186:mount][\<c01365b4\>] \(sys_mount+0x0/0xc0\) from [\<c000e800\>] \(ret_fast_syscall+0x0/0x30\)
[  652.635198] \(2\)[13186:mount] r7:00000015 r6:00000000 r5:00000000 r4:00000000
[  652.635226] \(2\)[13186:mount]machine_shutdown: done
[  652.635236] \(2\)[13186:mount]Reboot:machine restart...
[  652.637215] \(2\)[13186:mount]arch_reset: cmd = NULL
[  652.637436] \(2\)[13186:mount]wdt_arch_reset called@Kernel mode =
[  652.637902] \(2\)[13186:mount]wdt_arch_reset called MTK_WDT_MODE =5c
[  652.638369] \(2\)[13186:mount]wdt_arch_reset called end  MTK_WDT_MODE =22000014
-root@U65GT:/storage/sdcard0 #
root@U65GT:/storage/sdcard0 #
root@U65GT:/storage/sdcard0 #
root@U65GT:/storage/sdcard0 #
root@U65GT:/storage/sdcard0 # cat /proc/last_kmsg | grep -i exfat
[  652.634867] \(2\)[13186:mount][\<bf0591a0\>] \(exfat_fill_super+0x0/0x4b4 [exfat]\) from [\<c011acbc\>] \(mount_bdev+0x174/0x1dc\)
[  652.634911] \(2\)[13186:mount][\<c011ab48\>] \(mount_bdev+0x0/0x1dc\) from [\<bf059198\>] \(exfat_fs_mount+0x20/0x28 [exfat]\)
[  652.634955] \(2\)[13186:mount][\<bf059178\>] \(exfat_fs_mount+0x0/0x28 [exfat]\) from [\<c011b784\>] \(mount_fs+0x4c/0x194\)
root@U65GT:/storage/sdcard0 # cat /proc/kmsg | grep -i exfat
\<6\>[  523.636458] \(0\)[7154:insmod]exFAT: Version 1.2.9
login as: root
SSHD Server
root@90.189.123.100's password:
root@U65GT:/storage/sdcard0 # cat /proc/kmsg | grep -i exfat
\<6\>[  311.875760] \(1\)[5656:insmod]exFAT: Version 1.2.9
\<5\>[  390.990332] \(0\)[6042:adbd]type=1400 audit\(1421307895.740:1211\): avc:  denied  { setattr } for  pid=6042 comm="adbd" name="exfat.ko" dev="mmcblk0p5" ino=106511 scontext=u:r:adbd:s0 tcontext=u:object_r:system_file:s0 tclass=file
\<5\>[  391.188509] \(0\)[6117:busybox]type=1400 audit\(1421307895.940:1212\): avc:  denied  { setattr } for  pid=6117 comm="busybox" name="exfat.ko" dev="mmcblk0p5" ino=106511 scontext=u:r:shell:s0 tcontext=u:object_r:system_file:s0 tclass=file
\<6\>[  394.327102] \(1\)[6173:insmod]exFAT: Version 1.2.9
login as: root
SSHD Server
root@90.189.123.100's password:
root@U65GT:/storage/sdcard0 # cat /proc/last_kmsg
ram console header, hw_status: 2, fiq step 40.
bin log 0.
throttled                  : 0
[  402.396605] \(1\)[6286:mount]  .rt_time                       : 0.000000
[  402.396618] \(1\)[6286:mount]  .rt_runtime                    : 800.000000
[  402.396630] \(1\)[6286:mount]
[  402.396634] \(1\)[6286:mount]rt_rq[7]:/
[  402.396646] \(1\)[6286:mount]  .rt_nr_running                 : 0
[  402.396657] \(1\)[6286:mount]  .rt_throttled                  : 0
[  402.396670] \(1\)[6286:mount]  .rt_time                       : 0.000000
[  402.396683] \(1\)[6286:mount]  .rt_runtime                    : 950.000000
[  402.396695] \(1\)[6286:mount]
[  402.396700] \(1\)[6286:mount]runnable tasks:
[  402.396705] \(1\)[6286:mount]            task   PID         tree-key  switches  prio     exec-runtime         sum-exec        sum-sleep
[  402.396714] \(1\)[6286:mount]----------------------------------------------------------------------------------------------------------
[  402.406876] \(1\)[6286:mount]==========================================================================================================
[  402.406890] \(1\)[6286:mount]
[  402.407052] \(1\)[6286:mount]-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  402.761289] \(1\)[6286:mount][aee/ipanic] pc/lr/sp 0xb6e940a0/0xb6f16187/0xbeb75b60
[  402.761575] \(1\)[6286:mount][aee/ipanic] Dump stack range \(0xbeb75b60:0xbeb76000\)
[  402.761603] \(1\)[6286:mount][aee/ipanic] copy_from_user ret\(0x00000000\),len:4a0
[  402.769801] \(1\)[6286:mount][aee/ipanic] end dump native stack:
[  402.769909] \(1\)[6286:mount]-=-=-=
[  402.780649] \(1\)[6286:mount][aee/ipanic] ipanic_write_userspace: count 8463, strlen\(NativeInfo\):8463, off:286991
[  402.780675] \(1\)[6286:mount]-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  403.113318] \(1\)[6286:mount][aee/ipanic] ipanic_write_android_buf: dump droid log type 1, count 262144
[  403.113344] \(1\)[6286:mount]-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  403.444570] \(1\)[6286:mount][aee/ipanic] ipanic_write_android_buf: dump droid log type 3, count 262144
[  403.444595] \(1\)[6286:mount]-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  403.780763] \(1\)[6286:mount][aee/ipanic] ipanic_write_android_buf: dump droid log type 4, count 262144
[  403.780782] \(1\)[6286:mount]-=
[  403.781406] \(1\)[6286:mount][aee/ipanic] aee-ipanic: Panic dump sucessfully written to emmc \(detail len: 11404, console len: 262144\)
[  403.781431] \(1\)[6286:mount][aee/ipanic] android log : 0x46200, 0x40000, 0x0, 0x0, 0x86200, 0x40000, 0xc6200, 0x40000
[  403.781448] \(1\)[6286:mount][aee/ipanic] mmprofile: offset:0x106200, len:0x0
[  403.781464] \(1\)[6286:mount]Rebooting in 1 seconds..machine_shutdown: start, Proess\(mount:6286\)
[  404.779179] \(1\)[6286:mount]Backtrace:
[  404.779209] \(1\)[6286:mount][\<c001224c\>] \(dump_backtrace+0x0/0x10c\) from [\<c06fc8a0\>] \(dump_stack+0x18/0x1c\)
[  404.779224] \(1\)[6286:mount] r6:000003e8 r5:00000000 r4:000003e8 r3:c09e6018
[  404.779266] \(1\)[6286:mount][\<c06fc888\>] \(dump_stack+0x0/0x1c\) from [\<c000f844\>] \(machine_shutdown+0x34/0x50\)
[  404.779295] \(1\)[6286:mount][\<c000f810\>] \(machine_shutdown+0x0/0x50\) from [\<c000f8bc\>] \(machine_restart+0x14/0x64\)
[  404.779326] \(1\)[6286:mount][\<c000f8a8\>] \(machine_restart+0x0/0x64\) from [\<c0068038\>] \(emergency_restart+0x1c/0x20\)
[  404.779340] \(1\)[6286:mount] r5:00000000 r4:000003e8
[  404.779372] \(1\)[6286:mount][\<c006801c\>] \(emergency_restart+0x0/0x20\) from [\<c06fcd80\>] \(panic+0x138/0x1a0\)
[  404.779399] \(1\)[6286:mount][\<c06fcc48\>] \(panic+0x0/0x1a0\) from [\<c0012524\>] \(die+0x118/0x2ac\)
[  404.779413] \(1\)[6286:mount] r3:00000001 r2:cbdfdb60 r1:20070193 r0:c0852b08
[  404.779442] \(1\)[6286:mount] r7:00000001
[  404.779470] \(1\)[6286:mount][\<c001240c\>] \(die+0x0/0x2ac\) from [\<c06fc900\>] \(__do_kernel_fault.part.10+0x5c/0x7c\)
[  404.779497] \(1\)[6286:mount][\<c06fc8a4\>] \(__do_kernel_fault.part.10+0x0/0x7c\) from [\<c0015cc0\>] \(do_page_fault+0x224/0x270\)
[  404.779512] \(1\)[6286:mount] r7:df39c540 r3:cbdfdd70
[  404.779544] \(1\)[6286:mount][\<c0015a9c\>] \(do_page_fault+0x0/0x270\) from [\<c0015e34\>] \(do_translation_fault+0xa0/0xa8\)
[  404.779571] \(1\)[6286:mount][\<c0015d94\>] \(do_translation_fault+0x0/0xa8\) from [\<c00083ec\>] \(do_DataAbort+0x78/0x110\)
[  404.779586] \(1\)[6286:mount] r7:c09da8e4 r6:cbdfc000 r5:00000005 r4:cbdfdd70
[  404.779626] \(1\)[6286:mount][\<c0008374\>] \(do_DataAbort+0x0/0x110\) from [\<c000e258\>] \(__dabt_svc+0x38/0x60\)
[  404.779642] \(1\)[6286:mount]Exception stack\(0xcbdfdd70 to 0xcbdfddb8\)
[  404.779658] \(1\)[6286:mount]dd60:                                     ffffffff ca434100 00000001 00000000
[  404.779678] \(1\)[6286:mount]dd80: ca4340ec bf00fa3c c5babc00 ca430000 00000001 00000003 00000000 cbdfde2c
[  404.779696] \(1\)[6286:mount]dda0: 00000000 cbdfddb8 c00e8434 bf00925c 60070013 ffffffff
[  404.779709] \(1\)[6286:mount] r8:00000001 r7:cbdfdda4 r6:ffffffff r5:60070013 r4:bf00925c
[  404.779782] \(1\)[6286:mount][\<bf0091a0\>] \(exfat_fill_super+0x0/0x4c0 [exfat]\) from [\<c011acbc\>] \(mount_bdev+0x174/0x1dc\)
[  404.779827] \(1\)[6286:mount][\<c011ab48\>] \(mount_bdev+0x0/0x1dc\) from [\<bf009198\>] \(exfat_fs_mount+0x20/0x28 [exfat]\)
[  404.779871] \(1\)[6286:mount][\<bf009178\>] \(exfat_fs_mount+0x0/0x28 [exfat]\) from [\<c011b784\>] \(mount_fs+0x4c/0x194\)
[  404.779899] \(1\)[6286:mount][\<c011b738\>] \(mount_fs+0x0/0x194\) from [\<c0133b1c\>] \(vfs_kern_mount+0x50/0xe8\)
[  404.779925] \(1\)[6286:mount][\<c0133acc\>] \(vfs_kern_mount+0x0/0xe8\) from [\<c0134724\>] \(do_kern_mount+0x38/0xfc\)
[  404.779940] \(1\)[6286:mount] r8:d7d8f440 r7:00008000 r6:d7d8f7c0 r5:bf00fa44 r4:00000000
[  404.779972] \(1\)[6286:mount]r3:00000000
[  404.779999] \(1\)[6286:mount][\<c01346ec\>] \(do_kern_mount+0x0/0xfc\) from [\<c0135fc4\>] \(do_mount+0x334/0x854\)
[  404.780014] \(1\)[6286:mount] r8:d7d8f7c0 r7:00000020 r6:00000000 r5:00000000 r4:00008000
[  404.780045] \(1\)[6286:mount]r3:00000000
[  404.780072] \(1\)[6286:mount][\<c0135c90\>] \(do_mount+0x0/0x854\) from [\<c0136640\>] \(sys_mount+0x8c/0xc0\)
[  404.780099] \(1\)[6286:mount][\<c01365b4\>] \(sys_mount+0x0/0xc0\) from [\<c000e800\>] \(ret_fast_syscall+0x0/0x30\)
[  404.780113] \(1\)[6286:mount] r7:00000015 r6:00000000 r5:00000000 r4:00000000
[  404.780141] \(1\)[6286:mount]machine_shutdown: done
[  404.780151] \(1\)[6286:mount]Reboot:machine restart...
[  404.782136] \(1\)[6286:mount]arch_reset: cmd = NULL
[  404.782373] \(1\)[6286:mount]wdt_arch_reset called@Kernel mode =
[  404.782857] \(1\)[6286:mount]wdt_arch_reset called MTK_WDT_MODE =5c
[  404.783323] \(1\)[6286:mount]wdt_arch_reset called end  MTK_WDT_MODE =22000014

**Comment by dorimanx** [comment]
was made for samsung/LG/Asus/Nexus. MTK is not supported.

**Comment by mcirsta** [comment]
Lol, a file system driver is not made for a brand or a specific SOC. Of course if the error is indeed caused by something in the kernel code for that SOC but ....

**Comment by mlochd** [comment]
Hi, did anybody get exfat working on an mtk kernel?
