### ISSUE TITLE
Tag releases in git

### ISSUE THREAD

**Issue by Civil** [dorimanx/exfat-nofuse#66]
It'll be a lot easier for at least me, as user, to find stable releases if they had tags.

**Comment by dorimanx** [comment]
The last is the stable. No tags needed here.

**Comment by mcirsta** [comment]
Actually the man ( or woman )  is right, there should be releases. This thing about the last is stable doesn't really cut it, all respectable software projects have stable releases from time to time, even the Linux kernel.

**Comment by Civil** [comment]
Not every commit is version bump, that's why tags still needed, AFAIK.
