### ISSUE TITLE
wrong behaviour of directory link 

### ISSUE THREAD

**Issue by wisecrick** [dorimanx/exfat-nofuse#77]
I think exfat doesn't have support for file & directory link, but with this driver, you may create the links.

for example, I have a "foo" directory and foo\bar.dat file.
you may type

ln -s test foo

you will see a wrong symbolic link "temp" inside the foo directory.

and 

ln -s bar.dat tt 

also works.

Maybe these two should be disabled?

**Comment by dorimanx** [comment]
i think its was resolved. or no one interested...
