### ISSUE TITLE
Can't export exfat partition as nfs share

### ISSUE THREAD

**Issue by wisecrick** [dorimanx/exfat-nofuse#78]
On a archlinux system, I type these commands (My exfat partition is /dev/sda3):

mount /dev/sda3 /mnt/sda3 -o noatime,umask=000
mount --bind /mnt/sda3 /srv/nfs4/sda3
exportfs -arv

it will prompt:
exporting 192.168.89.0/24:/srv/nfs4/sda3
exportfs: /srv/nfs4/sda3 does not support NFS export
exporting 192.168.89.0/24:/srv/nfs4

my nfs exports file (/etc/exports) :
/srv/nfs4/         192.168.89.0/24(rw,fsid=root,no_subtree_check)
/srv/nfs4/sda3     192.168.89.0/24(rw,no_subtree_check,nohide)

So I want to know how can I share my exfat partition though nfs?
ps: exfat-fuse works, but it's slow due to fuse.

**Comment by dorimanx** [comment]
Well, if its say that nfs is not supported, then its not supported from day one.
If you want to add support, i will merge it.
