### ISSUE TITLE
full_name_hash changed

### ISSUE THREAD

**Issue by lgrootnoob** [dorimanx/exfat-nofuse#89]
in 4.8, (stringhash.c)full_name_hash now has three arguments instead of two. this causes compilation to fail.
from: extern unsigned int __pure full_name_hash(const char *, unsigned int);
to: extern unsigned int __pure full_name_hash(const void *salt, const char *, unsigned int);
in exfat_super.c this needs to be adjusted: qstr->hash = full_name_hash(qstr->name, exfat_striptail_len(qstr));

I might follow up with a (less than elegant) patch if nothing is proposed.

**Comment by dorimanx** [comment]
Please submit pull request with patch considering linux ver checks,  so its won't fail for lower linux builds.  Thanks.

**Comment by timofonic** [comment]
Any news?

**Comment by dorimanx** [comment]
Should be ok now. thanks for pull request.
